/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alpac;

import alpac.arraylist.MyArrayList;
import org.testng.annotations.*;

import java.util.Objects;

import static org.testng.Assert.*;

public class CapacityTests {

    private int EMPTY_ARRAY = 0;
    private int DEF_CAP = 16;

    @Test
    public void verifyArrayCreation() {
        MyArrayList<String> testAl = new MyArrayList();
        int size = testAl.size();
        assertEquals(EMPTY_ARRAY, size);
    }

    @Test
    public void verifyAddMethod() {
        MyArrayList<String> testAl = new MyArrayList();
        final String expected = "ABC";
        testAl.add(expected);
        final String actual = testAl.get(0);
        int size = testAl.size();
        assertEquals(size, 1);
        assertEquals(actual, expected);
    }

    @Test
    public void verifyMaxCapacityMethod() {
        MyArrayList<String> testAl = new MyArrayList();
        for (int i = 0; i < DEF_CAP; i++) {
            testAl.add(Objects.toString(i + 1));
        }
        int size = testAl.size();
        assertEquals(size, DEF_CAP);
    }

    @Test
    public void verifyMaxPlusOneCapacityMethod() {
        MyArrayList<String> testAl = new MyArrayList();
        for (int i = 0; i < DEF_CAP + 1; i++) {
            testAl.add(Objects.toString(i + 1));
        }
        int size = testAl.size();
        assertEquals(size, DEF_CAP + 1);
        assertEquals(testAl.get(DEF_CAP), "17");
    }




}
