/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alpac;

import alpac.arraylist.MyArrayList;
import org.checkerframework.checker.units.qual.A;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ArrayList<String> list = new ArrayList<>();
        String s = list.get(0);

    }

    @Override
    public String toString() {
        return "super.toString()srfafawefaedqfwe";
    }
}
